INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG000', 'Core', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG001', 'Enhanced datetime facilities', 'YES', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG002', 'Enhanced integrity management', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG003', 'OLAP facilities', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG004', 'PSM', 'NO', null, 'PL/pgSQL is similar.');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG005', 'CLI', 'NO', null, 'ODBC is similar.');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG006', 'Basic object support', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG007', 'Enhanced object support', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG008', 'Active database', 'NO', null, '');
INSERT INTO information_schema.sql_packages (feature_id, feature_name, is_supported, is_verified_by, comments) VALUES ('PKG010', 'OLAP', 'NO', null, 'NO');