INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('BINDIR', 'C:/PROGRA~1/POSTGR~1/11/bin');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('DOCDIR', 'C:/PROGRA~1/POSTGR~1/11/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('HTMLDIR', 'C:/PROGRA~1/POSTGR~1/11/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR', 'C:/PROGRA~1/POSTGR~1/11/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGINCLUDEDIR', 'C:/PROGRA~1/POSTGR~1/11/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR-SERVER', 'C:/PROGRA~1/POSTGR~1/11/include/server');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBDIR', 'C:/PROGRA~1/POSTGR~1/11/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGLIBDIR', 'C:/PROGRA~1/POSTGR~1/11/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LOCALEDIR', 'C:/PROGRA~1/POSTGR~1/11/share/locale');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('MANDIR', 'C:/Program Files/PostgreSQL/11/man');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SHAREDIR', 'C:/PROGRA~1/POSTGR~1/11/share');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SYSCONFDIR', 'C:/Program Files/PostgreSQL/11/etc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PGXS', 'C:/Program Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CONFIGURE', '--enable-thread-safety --enable-nls --with-ldap --with-openssl --with-ossp-uuid --with-libxml --with-libxslt --with-icu --with-tcl --with-perl --with-python');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CC', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CPPFLAGS', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS_SL', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_EX', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_SL', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBS', 'not recorded');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('VERSION', 'PostgreSQL 11.4');